name: lume-demo-repo-dev
channels:
  - conda-forge
dependencies:
  - click
  - pydantic # until lume-services registered with conda
  - lume-model>=1.4 # until lume-services registered with conda
  - graphviz
  - python-graphviz
  - prefect[viz]<2.0
  - pip 
  - pip: 
    - git+https://github.com/slaclab/lume-services.git@main

  # dev
  - pre-commit
  - pytest
  - pytest-cov
  - jupyterlab
  - numpy
