name: lume-demo-repo
channels:
  - conda-forge
dependencies:
  - prefect<2.0 # until lume-services registered with conda
  - lume-model>=1.4 # until lume-services registered with conda
  - pip 
  - pip: 
    - git+https://github.com/slaclab/lume-services.git@main
  - numpy
